[package]
name = "breathe"
version = "0.1.0"
authors = ["Luca Pizzamiglio <pizzamig@FreeBSD.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1", features = [ "attributes", "unstable" ] }
strum = { version = "0.20", features = ["derive"] }
indicatif = "0.15"
